version: '2'

services:
  pg:
    image: postgres:13-alpine
    ports:
      - 5432:5432
    volumes:
      - ./db/pgdatabase:/var/lib/postgresql
    environment:
      POSTGRES_USER: "andrii"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "test"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
